export const food = {
  rice: [
    { name: "Thakkali Soru " },
    { name: "Sambar Soru " },
    { name: "Thengai Soru " },
    { name: "Milagu Soru " },
    { name: "Paruppu Soru " },
    { name: "Karuvepillai Soru " },
    { name: "Thayir Soru " },
    { name: "Nei Soru " },
    { name: "Urulai Soru " },
    { name: "Muttaikos Soru " },
    { name: "Kudaimilagai Soru " },
    { name: "Kootansoru " },
    { name: "Kothamalli Pudina Soru " },
    { name: "Manga Soru " },
    { name: "Thatta payaru arisi paruppu Soru " },
    { name: "Vetrilai poondu Soru " },
    { name: "Brinji Soru" },
    { name: "Elumichai Soru (Lemon rice) " },
    { name: "Ghee pongal" },
    { name: "Sweet pongal" },
    { name: "Kalkandu pongal" },
    { name: "Puli pongal " },
    { name: "Thinai pongal " },
  ],
  sambar: [
    { name: "Ladiesfinger sambar" },
    { name: "Potato, tomato and carrot sambar" },
    { name: "Carrot and beans sambar" },
    { name: "Arachuvitta sambar" },
    { name: "Bitter gourd pitlai" },
    { name: "Sambar for idly/dosa/pongal" },
    { name: "Mango Sambar" },
    { name: "Mixed Vegetable Sambar" },
    { name: "Vendhaya Keerai sambar" },
    { name: "Brinjal Sambar" },
    { name: "Onion Arachu vitta Sambar" },
    { name: "Drumstick Sambar Iyer style (without onions)" },
    { name: "Pasi Paruppu Sambar (tiffin sambar)" },
    { name: "No Onion No garlic Carrot Sambar" },
    { name: "Keerai Thandu Sambar" },
    { name: "Mor Sambar/Curd Sambar" },
  ],
  rasam: [
    { name: "Lemon rasam" },
    { name: "Paruppu rasam (tomato rasam)" },
    { name: "Cumin rasam" },
    { name: "Garlic rasam" },
    { name: "Kollu Rasam (horse gram rasam)" },
    { name: "Pepper rasam" },
    { name: "Pineapple rasam" },
    { name: "Tomato rasam" },
    { name: "Neem flower (Veppam Poo) rasam" },
    { name: "Kandathippili (pepper) rasam" },
    { name: "Mint rasam" },
    { name: "Beetroot tomato rasam" },
    { name: "Mutton elumbu rasam/Mutton bone rasam" },
  ],
  curry: [
    { name: "Thatta payaru kathirikkai kozhambu/Cow pea Brinjal curry" },
    { name: "Murunga keerai kozhambu/Drumstick leaves curry" },
    { name: "Pidukkam paruppu kozhambu/Shelled field beans curry" },
    { name: "Kaalan kozhambu/Mushroom curry" },
    { name: "Vendhaya kozhambu/Fenugreek seeds curry" },
    { name: "Mochai kozhambu/Field beans curry" },
    { name: "Pattani kuzhambu/Dry peas curry" },
    { name: "Ennai kathrikkai kozhambu/Oily eggplant spicy curry" },
    { name: "Vendaikkaai kaara kozhambu/Ladies finger spicy curry" },
    { name: "Kathrikkai kaara kozhambu/Brinjal spicy curry" },
    { name: "Mulai payaru kozhambu/Moong sprouts curry" },
    { name: "Ulli theeyal/Onion theeyal curry" },
    { name: "Kadalai theeyal/Channa theeyal curry" },
    { name: "Murungakkai theeyal/Drumstick theeyal curry" },
    { name: "Mochai theeyal/Field beans theeyal curry" },
    { name: "Poondu theeyal/Garlic theeyal curry" },
    { name: "Peerkangaai paal kozhambu/Ridgegourd curry" },
    { name: "Kollu kozhambu/Horse gram curry" },
    { name: "Keera kadaisal/Spinach smash curry" },
    { name: "Avarakkai paruppu kuzhambu/Broad beans lentil curry" },
    { name: "Milagai mandi/Green chilli curry" },
    { name: "Kaaramani puli kozhambu/Black eyed tamarind curry" },
    { name: "Urundai kozhambu/Lentil dumplings curry" },
    { name: "Murungakkai puli kozhambu/Drumstick tamarind curry" },
    { name: "Poondu kozhambu/Garlic tamarind curry" },
    { name: "Poosani paruppu kootu/Pumpkin lentil curry" },
    { name: "Vatha kozhambu/Turkey berry, black night shade curry" },
    { name: "Soya kozhambu/Soya curry" },
    { name: "Sakkarai valli kizhangu kozhambu/Sweet potato curry" },
    { name: "Pavakkaai pitla/Bittergourd curry" },
    { name: "Pavakkaai puli kozhambu/Bitter gourd tamarind curry" },
    { name: "Jeeraga kozhambu/Jeera seeds curry" },
    { name: "Milagu kozhambu/Pepper corns curry" },
    { name: "Karunai kizhangu kozhambu/Yam curry" },
  ],
  stirFry: [
    { name: "Parangikkaai ellu poriyal/Pumpkin fry curry with sesame seeds" },
    { name: "Arasanikaai poriyal/Yellow pumpkin fry" },
    { name: "Sorakkaai verkaadalai poriyal/Calabash peanuts fry" },
    { name: "Kizhangu pottalam/Madurai potato fry masala" },
    { name: "Senai kizhangu poriyal/Yam roast in banana leaves" },
    { name: "Urulai milagu varuval/Potato pepper fry" },
    { name: "Senai chops/Yam chops" },
    { name: "Vengaaya thalai poriyal/Spring onion fry" },
    { name: "Murungakeerai poriyal/Drumstick leaves fry" },
    { name: "Urulai podimaas/Potato podimas" },
    { name: "Ennai kathrikkaai masala/Stuffed small eggplant oily masala" },
    { name: "Chinna vengaayam poriyal/Shallots fry" },
    { name: "Kaaramani poriyal/Yard long beans fry" },
    { name: "Carrot beans thovaran/Carrot beans in coconut masala fry" },
    { name: "Vendhaya keerai kadalai poriyal/Methi leaves channa fry" },
    { name: "Cheppankizhangu varuval/Arbi fry" },
    { name: "Chettinad urulai poriyal/Chettinad spicy potato fry" },
    {
      name: "Chettinad urulai pattani poriyal/Chettinad spicy potato peas fry",
    },
    { name: "Agathi keerai poriyal/Agathi keerai fry" },
    { name: "Avarakkai poriyal/Broad beans coconut fry" },
    { name: "Kovakkai poriyal/Ivy gourd fry" },
    { name: "Carrot kose poriyal/Carrot cabbage fry" },
    { name: "Kaalan milagu varuval/Mushroom pepper fry" },
    { name: "Vendakkaai poriyal/Ladiesfinger fry" },
    { name: "Beetroot poriyal/Beetroot coconut fry" },
    { name: "Chow chow poriyal/Chayote squash fry" },
    { name: "Vaazhakkai podimas/Raw banana fry" },
    { name: "Peerkangaai poriyal/Ridgegourd fry" },
    { name: "Mullangi poriyal/Raddish fry" },
    { name: "Maravalli kizhangu poriyal/Tapioca stir fry" },
    { name: "Thanneer muttaan kizhangu poriyal/Asparagus fry" },
    { name: "Pudalangaai poriyal/Snake gourd fry" },
    { name: "Payaru thovaran/Green gram fry" },
    { name: "Pappaalikkai poriyal/Raw pappaya fry" },
    { name: "Vendhaya keerai poriyal/Fenugreek leaves fry" },
    { name: "Vendhaya keerai poriyal/Fenugreek leaves fry" },
    { name: "Kudaimilagaai milagu poriyal/Capsicum pepper fry" },
    { name: "Cauliflower milagu pirattal/Cauliflower pepper fry" },
    { name: "Ratha poriyal/Goat's blood fry" },
  ],
  stew: [
    { name: "Vaazhaipoo kootu/Plantain flower stew" },
    { name: "Vendakkai kootu/Ladiesfinger stew" },
    { name: "Murungakeerai paruppu usili/Drumstick leaves lentil stew" },
    { name: "Paruppu beans usili/Beans and lentils stew" },
    { name: "Kootaviyal/Aviyal cooked with all country veggies" },
    { name: "Keerai mandi/Chettinad spinach stew" },
    { name: "Sorakkaai kootu/Bottle gourd stew" },
    { name: "Vaazhai thandu kootu/Plantain stem curd stew" },
    { name: "Keerai paruppu poondu kootu/Spinach lentil garlic stew" },
    { name: "Mulakeerai kootu/Amarnath leaves lentil stew" },
    { name: "Pudalangai kootu/Snake gourd stew" },
    { name: "Kothavarangaai kootu/Cluster beans stew" },
    { name: "Poosanikkai kootu/Yellow pumpkin lentil stew" },
    { name: "Manathakkaali keera kootu/Black night shade leaves lentil stew" },
    { name: "Chow chow kootu/Chayote squash stew" },
    { name: "Thakkali kaai kootu/Green tomato lentil stew" },
    { name: "Kathrikkai rasavaangi/Eggplant lentil stew" },
    { name: "Mor keerai kootu/Buttermilk spinach stew" },
    { name: "Muttaikose kootu/Cabbage lentil stew" },
    { name: "Pachai payaru kootu/Moong bean stew" },
    { name: "Poosanikaai mor kootu/Ash gourd curd stew" },
    { name: "Chenaikizhangu kootu/Elephant yam stew" },
    { name: "Kadamba kootu/Mixed vegetable stew" },
    { name: "Noolkol kootu/Kohlrabi stew" },
    { name: "Tirunelveli Sodhi" },
    { name: "Murungakkai kootu/Drumstick lentil stew" },
    { name: "Avarakkaai kootu/Broadbeans lentil stew" },
    { name: "Kathrikka kootu/Brinjal stew" },
    { name: "Sutta kathirkkai Gotsu/Burnt Brinjal stew" },
    { name: "Parangikkaai paal kootu/Pumpkin stew in coconut milk" },
    { name: "Pappaalikkaai kootu/Raw pappaya stew" },
    { name: "Palakkaai kootu/Raw Jackfruit stew" },
    { name: "Vallaarai keerai kootu/Brahmi booti stew" },
  ],
  chicken: [
    { name: "Arachivitta kozhi curry/Chicken in spicy thick coconut gravy" },
    {
      name:
        "Varuthu aracha kozhi curry/Chicken in spicy fried and ground coconut gravy",
    },
    { name: "Kozhi milagu varuval/Chicken pepper fry" },
    { name: "Kozhi vellai kuruma/Chicken in white gravy" },
    { name: "Chicken65" },
    { name: "Chicken pakora" },
    { name: "Chicken sukka" },
    { name: "Chicken ghee roast" },
    { name: "Kozhi milagu masala/Chicken pepper masala" },
    { name: "Naatu Kozhi kuzhambu/Country chicken curry" },
    { name: "Naatu kozhi rasam/Chicken soup" },
    { name: "Chicken Chinthamani" },
    { name: "Kozhi pachai curry/Chicken corriander and mint curry" },
    { name: "Pallipaalayam chicken fry" },
    { name: "Chicken Kola urundai kozhambu/Chicken dumplings curry" },
    { name: "Madras kozhi kozhambu/Madras chicken curry" },
    { name: "Chicken chettinad" },
    {
      name:
        "Seeraga samba chicken biryani/Chicken biryani cooked with Seeraga samba rice",
    },
    { name: "Ambur chicken biryani" },
    { name: "Thalapakkatti chicken biryani" },
    { name: "Chicken 65 biryani" },
    { name: "Kovai biriyani" },
  ],
  mutton: [
    { name: "Aatukkal paaya/Mutton trotters stew" },
    { name: "Nenju elumbu soup/Mutton rib bones soup" },
    { name: "Mutton kuzhambu/curry" },
    { name: "Mutton korma in thick coconut gravy" },
    { name: "Mutton in fried ground coconut gravy" },
    { name: "Muttom elumbu rasam/Mutton bone soup" },
    { name: "Nalli elumbu masala/Goat Bone marrow masala" },
    { name: "Mutton curry dosa" },
    { name: "Ratha poriyal/Goat blood fry" },
    { name: "Mutton Sukka" },
    { name: "Mutton milagu varuval/Mutton pepper fry" },
    { name: "Mutton Kola urundai kozhambu/Muttom dumplings curry" },
    { name: "Kongunaadu vella mutton biryani/Kongunaad White mutton biryani" },
    {
      name:
        "Seeraga samba mutton biryani/Mutton biryani cooked with Seeraga samba rice",
    },
    { name: "Ambur Mutton biryani" },
    { name: "Thalapakkatti Mutton biryani" },
  ],
  seaFood: [
    { name: "Meen puli muzham/Fish in thick coconut tamarind gravy" },
    {
      name:
        "Meen karutha curry/Fish black curry[in fried coconut, shallots, garlic, dried ginger,peppercorns, corriander seeds, red chillies, oregano and other spices]",
    },
    { name: "Thengai paal meen curry/Fish in spicy coconut milk gravy." },
    { name: "Sura puttu/Fishpittu" },
    { name: "Iraal masala/Prawn spicy masala" },
    { name: "Iraal milagu varuval/ Spicy prawn pepper fry" },
    { name: "Coconut fish fry" },
    { name: "Nethili meen curry/White bait/anchovies curry" },
    { name: "Nethili meen varuval/Spicy deep fried anchovies" },
    { name: "Prawn ghee roast" },
    { name: "Fish briyani" },
    { name: "Prawn briyani" },
    { name: "Meen maanga curry/ Fish mango curry" },
    { name: "Spicy chettinad prawn masala" },
    { name: "Fish curry in ginger and coconut milk" },
    { name: "Spicy Vanjaram fry/Spicy salmon fry" },
    { name: "Chettinad fish curry" },
    { name: "Nandu masala/Crab curry" },
    { name: "Nandu omelette/Crab omelette" },
    { name: "Nandu rasam/Crab soup" },
  ],
  egg: [
    { name: "Muttai thokku/Egg masala" },
    { name: "Muttai aviayal/Egg aviyal" },
    { name: "Muttai milagu varuval/Egg pepper fry" },
    { name: "Chettinad spicy egg curry" },
    { name: "Muttai paniyaaram/Egg Paniyaaram" },
    { name: "Odachi oothina muttai curry/ Egg poached curry" },
    { name: "Muttai kalakki/Egg Kalakki" },
    { name: "Muttai korma" },
    { name: "Egg in thick coconut milk gravy" },
    { name: "Egg in spicy coconut and tamarind gravy" },
  ],
  sweets: [
    { name: "Arisi thengai payasam/Rice coconut pudding" },
    { name: "Pasiparuppu paaysam/Moong dhal pudding" },
    { name: "Kadalai paruppu paayasam/channa dhal pudding" },
    { name: "Aval paayasam/Puffed rice pudding" },
    { name: "Khasa khasa paayasam/Poppy seeds pudding" },
    { name: "Vazhai pazha paayasam/Banana pudding" },
    { name: "Adai Paayasam/Cooked rice flakes pudding" },
    { name: "Paal Paayasam/Milk pudding" },
    { name: "Thengai Paayasam/Coconut pudding" },
    { name: "Pala pazha Paayasam/Jackfruit pudding" },
    { name: "Mampazha paayasam/Mango pudding" },
    { name: "Javvarisi paaysam/Tapioca sago pudding" },
    { name: "Samba godhumai paayasam/Cracked wheat pudding" },
    { name: "Semiya paayasam/Vermicelli pudding" },
    { name: "Thinai paaysam/Foxtail millet pudding" },
    { name: "Carrot paayasam/Carrot pudding" },
    { name: "Badam paayasam/Badam pudding" },
    { name: "Rice paayasam/Rice pudding" },
    { name: "Sorakkai paayasam/Calabash pudding" },
    { name: "Elaneer paaysam/Tender coconut pudding" },
    { name: "Brown rice kheer" },
    { name: "Sweet potato kheer" },
    { name: "Apple kheer" },
    { name: "Thengai bholi/Coconut bholi" },
    { name: "Paasi paruppu bholi/Moong dhal bholi" },
    { name: "Then mittai/Honey comb sweet" },
    { name: "Ingi marappa/Ginger fudge" },
    { name: "Pori urundai/Puffed rice jaggery balls" },
    { name: "Kadalai mittai/Peanut jaggery balls" },
    { name: "Maalaadu/Roasted channa dhal sweet balls" },
    { name: "Paasi paruppu laddu/Moong dhal sweet balls" },
    { name: "Ravalaadu/Rava sweet balls" },
    { name: "Thinai laddu/Fox millet sweet balls" },
    { name: "Godhumai laddu/Wheat sweet balls" },
    { name: "Raagi nilakadalai laddu/Raagi peanut balls" },
    { name: "Ellurundai/Black sesame seeds sweet balls" },
    { name: "Vella elluruandai/White sesame seeds sweet balls" },
    { name: "Coconut laddu/Coconut sweet balls" },
    { name: "Aval laddu/Poha sweet balls" },
    { name: "Sweet somas" },
    { name: "Suyyam" },
    { name: "Kadharppam" },
    { name: "Mangaadi/Sweet mango in jaggery stew" },
    { name: "Sakkapalathirattu/Jack fruit in jaggery stew" },
    { name: "Thirattu paal/Paalguva" },
    { name: "Palambali/Kongunaadu style rice pudding" },
    { name: "Apppam" },
    { name: "Nei appam" },
    { name: "Unni appam" },
    { name: "Ammini appam" },
    { name: "Adhirasam" },
    { name: "Aravanai" },
    { name: "Paal kozhukattai" },
    { name: "Pazham Paniyaram" },
    { name: "Sakkarai kozhukattai" },
    { name: "Sakkarai Pongal/Sweet pongal" },
    { name: "Aval pongal" },
    { name: "Kalkandu pongal/Sugar candy pongal" },
    { name: "Sweet seedai" },
    { name: "Puttamudhu" },
    { name: "Mundhiri Kothu" },
    { name: "Akkaravadisal" },
    { name: "Jangiri" },
    { name: "Rava Kesari" },
    { name: "Pineapple kesari" },
    { name: "Mango kesari" },
    { name: "Aval kesari" },
    { name: "Halwa varieties " },
  ],
};
